apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/overlays/openshift_vault?ref=746d3cd4eabe29ff09d3f33b2f18d8b2496c760e

namespace: spi-system

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: 746d3cd4eabe29ff09d3f33b2f18d8b2496c760e
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: 746d3cd4eabe29ff09d3f33b2f18d8b2496c760e

patches:
  - target:
      kind: ConfigMap
      name: oauth-service-environment-config
    path: oauth-service-config-patch.json
  - target:
      kind: ConfigMap
      name: shared-environment-config
    path: config-patch.json
  - target:
      kind: Deployment
      name: spi-controller-manager
    path: operator-limits-patch.json
  - path: delete-shared-configuration-file.yaml
